### ISSUE TITLE
Aspect ratio metadata

### ISSUE THREAD

**Issue by pyby** [SRGSSR/srgdataprovider-apple#27]
### Issue type

Feature request

### Description of the problem

IL API add an aspect ratio property on the chapter object.

As a user, I would like to have it.

### Environment information

* Library version: 7.0.0
* iOS version: Any
* Device: Any

### Sample

https://il.srgssr.ch/integrationlayer/2.0/mediaComposition/byUrn/urn:srf:video:8c42d058-c2a0-406f-8ff8-26a4386fd4ae

- Key: aspectRatio
- Type: string
- Mandatory: false
- Value: Enum:[ `1:1`, `4:5`, `4:3`, `16:9` ]

**Comment by pyby** [comment]
Proposition on `feature/aspect-ratio` with a `SGSize`.

We should ask IL team about:
- audio content: empty value is ok?
- all videos content, from all BUs: default value `16:9`?

**Comment by defagos** [comment]
After discussion:

- The aspect ratio will be returned as a scalar value, readily available for use (e.g. assigning as constant of a layout constraint).
- We see little value in returning a user-friendly `numerator:denominator` value. Internally, the aspect ratio information is therefore simply parsed into a scalar as well.
- For audio content and BUs which do not currently return this information, we return `SRGAspectRatioUndefined`.
- Presentation layers (e.g. Letterbox) should check this information and choose an appropriate default behavior if the aspect ratio is undefined (e.g. 16:9 fallback).

**Comment by defagos** [comment]
The branch has been reviewed and is ready to be merged, but we decided to postpone the delivery so that Letterbox with aspect ratio support is delivered at the same time.

**Comment by defagos** [comment]
Merged into `develop`.
